server:
  port: 8083

spring:
  application:
    name: ms-cursos
  datasource:
    url: jdbc:postgresql://postgres:5432/ms-cursos
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
