server:
  port: 8082

spring:
  application:
    name: ms-usuarios
  datasource:
    url: jdbc:postgresql://postgres:5432/ms-usuarios
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
